#!/bin/bash
#SBATCH -J shallow
#SBATCH -o /home/jz853/shallow-water-project/results/mpi/shallow_mpi.out
#SBATCH -e /home/jz853/shallow-water-project/results/mpi/shallow_mpi.err
#SBATCH --nodes=4
#SBATCH --ntasks=96
#SBATCH --tasks-per-node=24
#SBATCH --cpus-per-task=1 
#SBATCH --get-user-env 
#SBATCH -t 00:5:00 
#SBATCH --mem-per-cpu=1000 
#SBATCH --partition=debug

source /etc/profile.d/modules.sh 
cd $HOME/shallow-water-project
mpirun -n 81 src/lshallow tests.lua dam 1000 4 112

