#!/bin/bash
#SBATCH -J shallow
#SBATCH -o results/baseline/strong/shallow_4n.out
#SBATCH -e results/baseline/strong/shallow_4n.err
#SBATCH --nodes=4 
#SBATCH --ntasks=4 
#SBATCH --tasks-per-node=1 
#SBATCH --cpus-per-task=1 
#SBATCH --get-user-env 
#SBATCH -t 00:10:00 
#SBATCH --mem-per-cpu=1000 
#SBATCH --partition=cs5220 

source /etc/profile.d/modules.sh 
#module load openmpi-4.0.0 
cd $HOME/projects/CS5220/shallow-water-project 
src/lshallow tests.lua dam 1000 

