#!/bin/bash
#SBATCH -J shallow
#SBATCH -o results/block/baseline/shallow_1n.out
#SBATCH -e results/block/baseline/shallow_1n.err
#SBATCH --nodes=1 
#SBATCH --ntasks=1 
#SBATCH --tasks-per-node=1 
#SBATCH --cpus-per-task=1
#SBATCH --nodelist=totient-cpu-02
#SBATCH --get-user-env 
#SBATCH -t 00:10:00 
#SBATCH --mem-per-cpu=1000 
#SBATCH --partition=cs5220 

source /etc/profile.d/modules.sh 
#module load openmpi-4.0.0 
cd $HOME/projects/CS5220/shallow-water-project 
src/lshallow tests.lua dam 400
